# -*- coding: utf-8 -*-
"""App1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hFntNp-zqr9au_enx1fPsfaLwQu_zokv
"""

import streamlit as st
import pickle
import os
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer # Corrected import statement
from sklearn.metrics.pairwise import cosine_similarity
VECTOR_FILE="/content/car.pkl"
CSV_FILE="/content/car_price_prediction_.csv"
THRESHOLD = 0.8
# Load the model
@st.cache_resource
def load_model():
    with open("car.pkl", "rb") as file:
        model = pickle.load(file)
    return model

model = load_model()

# Streamlit UI
st.title("🚗 Car Price Predictor")

# Input fields
brand = st.number_input("Brand (encoded as number)", min_value=0)
model_input = st.number_input("Model (encoded as number)", min_value=0)
year = st.number_input("Year", min_value=1900, max_value=2100, value=2020)
fuel_type = st.number_input("Fuel Type (encoded as number)", min_value=0)
mileage = st.number_input("Mileage (in km)", min_value=0)
engine_size = st.number_input("Engine Size (in CC)", min_value=0)

# Predict button
if st.button("Predict Price"):
    input_data = np.array([[brand, model_input, year, fuel_type, mileage, engine_size]])
    prediction = model.predict(input_data)
    st.success(f"Estimated Price: ₹{prediction[0]:,.2f}")