# -*- coding: utf-8 -*-
"""car price.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sv3-2pyLPimNFsvgqrCYwz2mru0c1jWp
"""

import pandas as pd

from sklearn.linear_model import LinearRegression

price = pd.read_csv("/content/car_price_prediction_.csv")

price.head()

price.isnull().sum()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le1=LabelEncoder()
le2=LabelEncoder()
price['Model']=le.fit_transform(price['Model'])
price['Brand']=le1.fit_transform(price['Brand'])
price['Fuel Type']=le2.fit_transform(price['Fuel Type'])

a=price[['Brand','Model','Year','Fuel Type','Mileage','Engine Size']]
b=price['Price']

LR=LinearRegression()

LR.fit(a,b)

LR.predict([[4,5,6,7,8,9]])